languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Kyle Capehart"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "Kyle Capehart Software Engineer Portfolio and Salesforce Blog"

[params.author]
  name = "Kyle Capehart"
  image = "img/kyle_circle.png"
  headline = "Software Engineer"
  bio = "I write code and such"
  links = [
    { email = "mailto:kyleacapehart@gmail.com" },
    { github = "https://github.com/k-capehart" },
    { linkedin = "https://www.linkedin.com/in/kyle-capehart/" }
  ]
