############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Software"
url = "/projects"
weight = 3

[[main]]
name = "Posts"
url = "/posts"
weight = 4

[[main]]
name = "Posts"
url = "/posts"
weight = 5

[[main]]
weight = 6
name = "Pages"

[[main]]
parent = "Pages"
name = "Contact"
url = "/contact"

[[main]]
parent = "Pages"
name = "Categories"
url = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1
